In [1]:
import pandas as pd
import numpy as np

In [2]:
def read_and_display(filepath):
    data = pd.read_csv(filepath, index_col='comp_id')
    print(data.shape)
    display(data.head())
    return data

In [3]:
desc_data_train = read_and_display("Description Data/train_desc_df.csv")

(3000, 50)

,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,desc_9,desc_10,...,desc_41,desc_42,desc_43,desc_44,desc_45,desc_46,desc_47,desc_48,desc_49,desc_50
comp_id,,,,,,,,,,,,,,,,,,,,,
1,-0.009555,0.002479,0.002927,0.015774,-0.008177,-0.016036,0.026697,-0.000106,0.025788,0.052237,...,-0.029430,-0.029423,0.052256,0.007814,0.023472,-0.021134,0.003324,-0.004393,0.004294,-0.002223
2,-0.009555,0.002479,0.002927,0.015774,-0.008177,-0.016036,0.026697,-0.000106,0.025788,0.052237,...,-0.029430,-0.029423,0.052256,0.007814,0.023472,-0.021134,0.003324,-0.004393,0.004294,-0.002223
3,-0.356706,0.213562,0.252663,0.090735,0.328961,-0.482705,0.067300,0.384217,-0.147253,-0.463378,...,-0.626436,-0.102908,0.576792,-0.805986,0.310637,0.422263,0.403496,0.264240,7.057590,-0.252417
4,-0.294013,0.165262,0.257102,0.421037,0.463214,-0.769155,0.159450,0.236385,-0.183974,-0.357842,...,-0.435836,0.052975,0.108777,-0.599593,0.408430,0.591615,0.415667,0.334706,7.025648,-0.309093
5,-0.028657,0.157017,0.282709,-2.674227,-0.711383,2.259387,-0.162175,0.605468,0.712229,0.027828,...,-1.714496,0.297421,-0.097744,0.000669,-1.639307,0.244313,0.099975,0.371806,-2.259024,-0.131085

In [4]:
desc_data_public = read_and_display("Description Data/public_desc_df.csv")

(986, 50)

,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,desc_9,desc_10,...,desc_41,desc_42,desc_43,desc_44,desc_45,desc_46,desc_47,desc_48,desc_49,desc_50
comp_id,,,,,,,,,,,,,,,,,,,,,
3001,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,-1.111625,0.252028,-0.193523,0.346493,-0.077318,0.276308,-0.045740,-0.007150,-3.448430,-0.031262
3002,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,-1.111625,0.252028,-0.193523,0.346493,-0.077318,0.276308,-0.045740,-0.007150,-3.448430,-0.031262
3003,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,-1.111625,0.252028,-0.193523,0.346493,-0.077318,0.276308,-0.045740,-0.007150,-3.448430,-0.031262
3004,-0.298706,-0.022012,0.552924,0.046070,0.044543,0.132187,-0.549770,1.437774,1.286943,1.445921,...,0.246156,-1.001942,-1.502183,1.105716,-0.170937,0.181976,0.437707,0.058352,-2.209322,0.104916
3005,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,-1.111625,0.252028,-0.193523,0.346493,-0.077318,0.276308,-0.045740,-0.007150,-3.448430,-0.031262

In [5]:
img_data_train = read_and_display("Image Data/train_image_df.csv")

(3000, 4000)

,image_1,image_2,image_3,image_4,image_5,image_6,image_7,image_8,image_9,image_10,...,image_3991,image_3992,image_3993,image_3994,image_3995,image_3996,image_3997,image_3998,image_3999,image_4000
comp_id,,,,,,,,,,,,,,,,,,,,,
1,0.484456,0.036087,-0.149328,0.144475,-0.617386,0.035018,0.169174,-0.005733,-0.104908,-0.041200,...,-0.090408,-0.032915,-0.010857,-0.015954,0.123416,0.195833,-0.066449,0.115818,-0.005140,0.017278
2,0.074533,-0.015655,-0.016286,-0.480964,0.687917,0.037131,-0.149725,-0.002098,0.099383,-0.021134,...,-0.625816,-0.009616,0.004558,0.008310,-0.173496,0.133518,-0.488898,0.084832,0.146566,0.007997
3,-0.396809,0.021490,-1.723037,0.666147,-0.631924,0.047724,0.336041,-0.003904,0.039683,0.002628,...,-0.078059,0.086320,-0.005606,0.002414,-0.164493,0.218473,0.151292,-0.076860,0.008321,0.012555
4,0.995316,0.012766,0.387472,-0.684791,-0.209261,0.013654,0.138517,0.005586,0.079277,-0.004665,...,-0.190714,-0.005452,-0.003889,0.013430,0.344406,0.038220,0.210446,-0.145128,-0.019172,0.000532
5,-0.611648,0.000860,-0.572393,0.894287,-0.191228,-0.111583,-0.011111,0.003231,-0.160582,0.032804,...,-0.040437,-0.142134,-0.022771,-0.013134,-0.024869,0.125129,0.215967,0.005288,0.145715,0.001425

In [6]:
img_data_public = read_and_display("Image Data/public_image_df.csv")

(986, 4000)

,image_1,image_2,image_3,image_4,image_5,image_6,image_7,image_8,image_9,image_10,...,image_3991,image_3992,image_3993,image_3994,image_3995,image_3996,image_3997,image_3998,image_3999,image_4000
comp_id,,,,,,,,,,,,,,,,,,,,,
3001,-0.288211,0.007964,-0.318695,-0.519448,-0.707238,0.018358,-0.127491,0.006911,-0.163305,-0.001028,...,0.095390,-0.005706,0.011662,0.027501,0.202042,0.031049,0.058993,0.085795,-0.033876,-0.010047
3002,-0.053049,-0.019362,-0.942308,0.971880,-0.145869,0.190100,0.323404,0.001693,0.052303,0.008241,...,-0.152575,-0.015299,0.006474,0.008779,0.064745,-0.130691,0.519738,-0.009965,0.226757,0.001792
3003,0.527363,0.027754,-1.644639,-0.362191,-0.275900,0.095907,-0.083026,-0.002009,0.041976,0.008518,...,-0.139857,0.056012,0.010546,-0.013047,0.395852,0.064757,0.061725,0.081311,0.094162,-0.015818
3004,0.709023,0.002011,-0.968376,0.478994,-0.451566,0.217366,-0.036373,0.004914,0.133615,0.019694,...,-0.343643,0.072151,0.045109,-0.009794,-0.002994,0.142427,-0.001836,0.116891,0.078607,-0.000430
3005,-0.349026,-0.060301,-1.099632,1.475574,-0.076292,0.153835,-0.143689,0.006389,0.058670,-0.021164,...,0.158350,-0.024394,0.002807,-0.004787,-0.012235,0.022360,0.034833,0.084962,-0.092006,0.010375

In [7]:
title_data_train = read_and_display("Title_Data/train_title_df.csv")

(3000, 50)

,title_1,title_2,title_3,title_4,title_5,title_6,title_7,title_8,title_9,title_10,...,title_41,title_42,title_43,title_44,title_45,title_46,title_47,title_48,title_49,title_50
comp_id,,,,,,,,,,,,,,,,,,,,,
1,-0.977637,-0.543310,0.079403,0.205560,-1.497104,0.230466,0.566112,-0.662264,0.130342,-0.277137,...,0.059434,-0.272340,-0.030180,-0.109040,-0.033425,0.728739,0.142030,0.397541,1.270722,-0.816523
2,0.041873,0.644655,0.140869,-0.664714,-0.062992,0.240086,-1.017593,1.019706,0.340133,0.617302,...,0.242961,-0.404538,0.335224,-0.158068,-0.178225,0.351125,0.959121,0.673848,-0.530106,0.133466
3,-0.905595,0.097928,0.111981,-0.064753,-1.566516,0.140807,-0.946588,-0.342442,0.031226,-0.660981,...,0.414191,-0.457968,0.157185,-0.116985,0.404937,-0.220503,0.443171,0.643445,0.357957,0.525154
4,0.069220,0.411544,0.177700,-0.739998,-0.932620,-0.717982,-0.406487,-0.267096,0.114066,-0.045532,...,0.211731,-0.812590,0.258014,-0.180143,-0.564691,-0.515378,0.613686,0.817547,0.325042,0.254415
5,0.503560,-0.210970,-0.085412,0.549240,-0.019521,-0.255597,0.841144,0.250485,0.224235,0.082816,...,-0.517912,0.543584,0.492052,-0.204867,-0.011538,-0.328607,-0.150055,-0.992373,-0.266003,-0.037134

In [8]:
title_data_public = read_and_display("Title_Data/public_title_df.csv")

(986, 50)

,title_1,title_2,title_3,title_4,title_5,title_6,title_7,title_8,title_9,title_10,...,title_41,title_42,title_43,title_44,title_45,title_46,title_47,title_48,title_49,title_50
comp_id,,,,,,,,,,,,,,,,,,,,,
3001,0.363698,0.309343,0.225138,0.318105,-0.523210,0.143360,-0.012829,0.407408,-0.048370,-0.298985,...,0.532943,0.194463,-0.635401,-0.419310,0.142901,-0.523376,1.204893,-1.413345,-0.096672,0.078235
3002,0.218130,1.117077,0.122527,-0.005565,-0.158261,0.390527,0.189782,0.685502,-0.383055,0.402898,...,0.548985,0.066296,-0.525967,-0.674784,0.151137,-1.065329,0.751027,-1.075753,-0.009242,0.464259
3003,0.209271,0.785080,0.287104,0.508236,0.306759,0.505576,-0.172887,0.324774,-0.032752,0.168677,...,0.803655,0.199135,-0.580919,-0.569989,0.033141,-0.658906,0.956579,-0.885134,-0.233097,0.235301
3004,1.160773,-0.491947,0.188722,-0.100140,-1.738414,-0.105218,0.400427,-0.216526,-0.371494,0.231583,...,0.125851,0.735062,0.330460,0.646128,0.809633,0.162228,0.274926,-0.085908,0.217528,1.031500
3005,1.338603,0.599431,0.519767,-0.198956,0.850357,0.039661,0.248881,0.885659,0.245418,-0.147505,...,0.531473,-0.406249,-0.507858,-0.187037,0.802942,-0.472328,0.897817,-1.227795,0.746802,-0.379223

In [9]:
meta_data_train = read_and_display("Metadata/train_meta_df.csv")

(3000, 13)

,ad_blocked,embed,ratio,duration,language,partner,partner_active,n_likes,views,n_tags,n_formats,dayofweek,hour
comp_id,,,,,,,,,,,,,
1,False,True,1.77778,86,3,True,False,0,290,3,0,5,6
2,False,True,1.33333,1129,2,True,False,0,1443,0,2,5,6
3,False,True,1.76667,1163,2,True,False,0,329,0,1,5,6
4,False,True,1.77778,1326,2,True,False,0,63,0,3,5,6
5,False,True,1.77273,2612,2,True,False,3,37,0,0,5,6

In [10]:
meta_data_public = read_and_display("Metadata/public_meta_df.csv")

(986, 12)

,ad_blocked,embed,ratio,duration,language,partner,partner_active,n_likes,n_tags,n_formats,dayofweek,hour
comp_id,,,,,,,,,,,,
3001,False,True,1.33333,1675,2,False,False,0,10,2,2,3
3002,False,True,1.33333,1479,2,False,False,0,10,2,2,3
3003,False,True,1.33333,1505,2,False,False,0,10,2,2,3
3004,False,True,1.77778,50,2,True,True,1,6,5,2,3
3005,False,True,1.33333,1543,2,False,False,0,6,2,2,3

In [11]:
train_data = pd.concat([desc_data_train, title_data_train, img_data_train, meta_data_train], axis=1)
print(train_data.shape)
train_data.head()

(3000, 4113)

,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,desc_9,desc_10,...,duration,language,partner,partner_active,n_likes,views,n_tags,n_formats,dayofweek,hour
comp_id,,,,,,,,,,,,,,,,,,,,,
1,-0.009555,0.002479,0.002927,0.015774,-0.008177,-0.016036,0.026697,-0.000106,0.025788,0.052237,...,86,3,True,False,0,290,3,0,5,6
2,-0.009555,0.002479,0.002927,0.015774,-0.008177,-0.016036,0.026697,-0.000106,0.025788,0.052237,...,1129,2,True,False,0,1443,0,2,5,6
3,-0.356706,0.213562,0.252663,0.090735,0.328961,-0.482705,0.067300,0.384217,-0.147253,-0.463378,...,1163,2,True,False,0,329,0,1,5,6
4,-0.294013,0.165262,0.257102,0.421037,0.463214,-0.769155,0.159450,0.236385,-0.183974,-0.357842,...,1326,2,True,False,0,63,0,3,5,6
5,-0.028657,0.157017,0.282709,-2.674227,-0.711383,2.259387,-0.162175,0.605468,0.712229,0.027828,...,2612,2,True,False,3,37,0,0,5,6

In [12]:
test_data = pd.concat([desc_data_public, title_data_public, img_data_public, meta_data_public], axis=1)
print(test_data.shape)
test_data.head()

(986, 4112)

,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,desc_9,desc_10,...,ratio,duration,language,partner,partner_active,n_likes,n_tags,n_formats,dayofweek,hour
comp_id,,,,,,,,,,,,,,,,,,,,,
3001,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,1.33333,1675,2,False,False,0,10,2,2,3
3002,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,1.33333,1479,2,False,False,0,10,2,2,3
3003,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,1.33333,1505,2,False,False,0,10,2,2,3
3004,-0.298706,-0.022012,0.552924,0.046070,0.044543,0.132187,-0.549770,1.437774,1.286943,1.445921,...,1.77778,50,2,True,True,1,6,5,2,3
3005,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,1.33333,1543,2,False,False,0,6,2,2,3

In [13]:
ad_blocked = train_data.select_dtypes(exclude=np.number)['ad_blocked'].value_counts()
embed = train_data['embed'].value_counts()
partner = train_data['partner'].value_counts()
partner_active = train_data['partner_active'].value_counts()

train_data['Encoded_ad_blocked'] = train_data['ad_blocked'].map(ad_blocked)
train_data['Encoded_embed'] = train_data['embed'].map(embed)
train_data['Encoded_partner'] = train_data['partner'].map(partner)
train_data['Encoded_partner_active'] = train_data['partner_active'].map(partner_active)

train_data[['ad_blocked', 'Encoded_ad_blocked', 'embed', 'Encoded_embed', 'partner', 'Encoded_partner', 'partner_active', 'Encoded_partner_active']].head()

,ad_blocked,Encoded_ad_blocked,embed,Encoded_embed,partner,Encoded_partner,partner_active,Encoded_partner_active
comp_id,,,,,,,,
1,False,2980,True,2982,True,1806,False,2317
2,False,2980,True,2982,True,1806,False,2317
3,False,2980,True,2982,True,1806,False,2317
4,False,2980,True,2982,True,1806,False,2317
5,False,2980,True,2982,True,1806,False,2317

In [14]:
train_data = train_data.drop(['ad_blocked','embed','partner','partner_active'], axis = 1)
train_data.head()

,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,desc_9,desc_10,...,n_likes,views,n_tags,n_formats,dayofweek,hour,Encoded_ad_blocked,Encoded_embed,Encoded_partner,Encoded_partner_active
comp_id,,,,,,,,,,,,,,,,,,,,,
1,-0.009555,0.002479,0.002927,0.015774,-0.008177,-0.016036,0.026697,-0.000106,0.025788,0.052237,...,0,290,3,0,5,6,2980,2982,1806,2317
2,-0.009555,0.002479,0.002927,0.015774,-0.008177,-0.016036,0.026697,-0.000106,0.025788,0.052237,...,0,1443,0,2,5,6,2980,2982,1806,2317
3,-0.356706,0.213562,0.252663,0.090735,0.328961,-0.482705,0.067300,0.384217,-0.147253,-0.463378,...,0,329,0,1,5,6,2980,2982,1806,2317
4,-0.294013,0.165262,0.257102,0.421037,0.463214,-0.769155,0.159450,0.236385,-0.183974,-0.357842,...,0,63,0,3,5,6,2980,2982,1806,2317
5,-0.028657,0.157017,0.282709,-2.674227,-0.711383,2.259387,-0.162175,0.605468,0.712229,0.027828,...,3,37,0,0,5,6,2980,2982,1806,2317

In [15]:
ad_blocked = test_data['ad_blocked'].value_counts()
embed = test_data['embed'].value_counts()
partner = test_data['partner'].value_counts()
partner_active = test_data['partner_active'].value_counts()

test_data['Encoded_ad_blocked'] = test_data['ad_blocked'].map(ad_blocked)
test_data['Encoded_embed'] = test_data['embed'].map(embed)
test_data['Encoded_partner'] = test_data['partner'].map(partner)
test_data['Encoded_partner_active'] = test_data['partner_active'].map(partner_active)

test_data[['ad_blocked', 'Encoded_ad_blocked', 'embed', 'Encoded_embed', 'partner', 'Encoded_partner', 'partner_active', 'Encoded_partner_active']].head()

,ad_blocked,Encoded_ad_blocked,embed,Encoded_embed,partner,Encoded_partner,partner_active,Encoded_partner_active
comp_id,,,,,,,,
3001,False,986,True,952,False,749,False,842
3002,False,986,True,952,False,749,False,842
3003,False,986,True,952,False,749,False,842
3004,False,986,True,952,True,237,True,144
3005,False,986,True,952,False,749,False,842

In [16]:
test_data = test_data.drop(['ad_blocked','embed','partner','partner_active'], axis = 1)
test_data.head()

,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,desc_9,desc_10,...,language,n_likes,n_tags,n_formats,dayofweek,hour,Encoded_ad_blocked,Encoded_embed,Encoded_partner,Encoded_partner_active
comp_id,,,,,,,,,,,,,,,,,,,,,
3001,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,2,0,10,2,2,3,986,952,749,842
3002,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,2,0,10,2,2,3,986,952,749,842
3003,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,2,0,10,2,2,3,986,952,749,842
3004,-0.298706,-0.022012,0.552924,0.046070,0.044543,0.132187,-0.549770,1.437774,1.286943,1.445921,...,2,1,6,5,2,3,986,952,237,144
3005,-0.266289,0.151930,0.188684,0.935617,0.021999,0.100940,0.107302,-0.055652,0.023322,-0.523113,...,2,0,6,2,2,3,986,952,749,842

In [17]:
y = train_data['views'].iloc[:-1].values
X = train_data.drop(['views'], axis = 1).iloc[:-1].values

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_squared_error, r2_score
from math import sqrt
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [19]:
lir = LinearRegression()

In [20]:
lir.fit(X_train,y_train)

LinearRegression()

In [21]:
ypred_lir = lir.predict(X_test)
print(ypred_lir)

[ 2.27981111e+08  1.40851056e+09 -3.65966420e+08  2.61088968e+09
 -1.09235160e+09  1.19780901e+09  2.31610676e+09 -1.69261744e+09
 -1.84155326e+09 -1.27811531e+09  8.43667387e+08 -2.86988169e+08
 -3.08331229e+09 -2.10882002e+09 -1.06872782e+09 -2.47648738e+08
 -5.74510759e+08  7.17787865e+08  2.99199721e+08  1.29662417e+09
  6.82050797e+07  1.29606833e+09 -2.35135068e+09  1.71849617e+02
 -8.29282900e+08  4.97068460e+07 -4.58507197e+08 -6.79689989e+08
  1.61849980e+02 -1.33027896e+09  2.58050498e+09  1.02383883e+09
  3.51544461e+08  2.41849885e+02  1.58064762e+08 -1.44300129e+09
 -3.39940441e+08  5.53429938e+08  2.37391001e+09 -2.44112021e+09
  1.81811685e+09  1.67849887e+02 -1.25386439e+09  1.21749187e+08
  4.61499348e+01  2.11739836e+09  5.09257096e+08  4.70219208e+08
 -2.72523113e+08  6.34474575e+07 -2.99397447e+08  1.16967303e+09
 -1.42359408e+09  1.06780253e+09 -2.15630753e+08  1.79758614e+09
  2.21363269e+09  4.31657796e+07 -1.73834356e+09  5.52443842e+08
 -1.20500642e+09  3.63321808e+08  2.15113311e+09 -1.99855156e+09
  3.12307571e+08  2.35898544e+09 -7.40936683e+08  5.43028786e+08
 -1.04048474e+09 -7.24250388e+08  3.84663257e+08 -1.99981100e+09
 -2.47807668e+09 -1.11500221e+09 -5.21968432e+07  1.77378903e+08
  7.54239491e+08  5.50766758e+08  2.10934979e+09  3.05017768e+08
 -3.72887552e+08  1.00144274e+08 -2.12428234e+09 -1.03300107e+09
 -1.21819810e+09 -6.93667645e+07 -3.90874597e+08  2.33812754e+09
 -2.12124660e+08  2.48897216e+07  4.32768949e+08 -7.12682984e+08
 -1.22295593e+08  2.92615444e+07 -1.44528132e+09  2.35561390e+08
  7.41685594e+08  6.61498690e+01  4.39831304e+08  7.84085150e+08
  1.69684372e+09  1.37306983e+07 -2.13503990e+07 -5.61796112e+08
  1.17752910e+09 -2.55483756e+09 -7.35246365e+08 -2.59128050e+09
  1.78849869e+02 -1.59237538e+08  1.06274884e+09  1.42940037e+09
  1.91246899e+09  2.10677335e+09  1.48972479e+08  1.80826757e+09
 -1.55342357e+09  8.64062065e+08 -6.30760374e+08 -3.93755160e+08
  2.27874446e+09 -2.54004386e+09  2.83402987e+08 -2.72313800e+09
 -9.32810194e+08  1.42053020e+09 -2.68389717e+09 -4.78372299e+08
 -5.77317834e+08  1.25075662e+09  6.46719054e+08 -1.04411394e+09
 -7.67598654e+08 -8.74069711e+08 -1.75034172e+09 -2.87246431e+08
  2.96447096e+08  2.96242816e+09 -1.28775136e+09 -1.98092692e+09
  9.97710173e+08 -1.25349214e+09  1.74249752e+09  1.76656605e+09
 -8.19512177e+08  6.69301169e+08  1.08308009e+09 -5.80089920e+08
  2.94175014e+09 -7.52847796e+08 -5.23922627e+08  1.37814235e+09
  9.74748938e+08  1.46261819e+08 -1.01924108e+09 -9.27571754e+08
  1.89439544e+09 -2.04171904e+08  7.51501245e+01  1.27522164e+09
 -6.42602281e+07 -8.91178453e+08 -2.28782456e+08 -3.54175127e+08
 -1.02395556e+09  6.89699754e+08  7.59870640e+08 -1.95209808e+07
  2.72003945e+08 -3.84878137e+08  7.90354537e+08  1.22855388e+09
 -1.53294970e+09  5.27083679e+08  4.66026758e+08 -2.02385592e+08
  1.46203408e+09 -1.61740250e+09  1.70356432e+08  9.06334862e+08
 -1.60805712e+09 -1.53111887e+09  1.76460863e+09 -1.16430710e+09
 -7.95049852e+08 -5.74523973e+08 -2.13238509e+09 -1.66198512e+09
 -1.16305704e+09 -1.01960693e+09 -1.06617317e+09  2.12466150e+08
  1.67590284e+09 -1.44333736e+09 -5.43360370e+08  2.54965110e+09
  2.41556650e+09 -8.86999346e+08 -2.98163446e+08  8.13770294e+08
  1.76126928e+09  8.91559340e+08 -8.78627714e+08  1.19266051e+09
 -2.78184099e+09 -2.18978091e+09  7.07811558e+08  6.74227246e+07
  7.82694500e+08 -6.67098587e+08 -3.36690899e+09  5.83261107e+07
 -1.79164761e+07 -1.42124473e+09 -1.33647007e+09 -7.16949682e+08
 -5.42946211e+07 -7.38541492e+08  2.50699538e+02 -7.34068267e+07
 -1.44282808e+09  3.12531633e+09  2.56734489e+08  4.53501867e+08
  7.24875819e+08 -5.26404635e+08 -2.36756590e+09  4.20467313e+09
  2.03770585e+08 -7.90197010e+08  2.42589065e+09  1.32265105e+09
  1.71774783e+02  6.51169062e+08 -1.75166540e+09  9.37212453e+08
  1.91261593e+08  8.74370122e+08  2.45282693e+08  4.92226046e+08
  7.65051270e+07 -9.58095246e+08  1.80566787e+09 -1.67375673e+09
 -1.23132186e+08 -1.52255658e+09 -1.13928803e+09  4.72247895e+09
 -8.85829918e+07  2.75557657e+09  4.61557283e+08 -4.89278721e+08
 -6.13807923e+08 -2.16280597e+09 -5.56711309e+08  2.76504640e+08
  6.50830959e+08  5.14989884e+08  5.51498370e+01 -2.90010087e+08
 -1.39087390e+09 -2.79276018e+09 -1.86087402e+09  2.20141318e+09
 -1.64467925e+09 -2.91515737e+09 -1.00802992e+09 -2.87455576e+08
 -3.47239836e+08 -1.98092682e+09 -4.12029785e+08  1.89251288e+09
  1.23955318e+09  4.23937327e+07  5.50766704e+08  5.27169663e+07
  4.05498364e+09 -1.07808641e+08  1.10064677e+09  3.79499898e+03
 -8.27856203e+08  1.70227240e+09  2.89536839e+09 -9.88161766e+08
 -8.30024102e+08  1.28026034e+09  2.16998978e+09  2.04621599e+09
  1.76858483e+09  4.59154160e+07  3.88890345e+08 -1.47377399e+08
  8.01501384e+01  4.45160606e+08 -5.06225780e+08  6.36203478e+07
 -6.54551953e+08 -1.76029201e+09  6.94641583e+08  3.09461753e+08
 -2.99620310e+09 -3.36749053e+08 -3.64819824e+08 -3.98048961e+08
  4.68687549e+08  1.84356176e+09  3.38358658e+09  2.47186066e+09
  9.72120810e+08  1.76294936e+09  4.81049898e+08  1.48855587e+09
  7.67603798e+08  5.94309410e+08  7.35353630e+08  8.43329804e+06
 -1.13788447e+09  2.43648546e+09 -2.72107980e+08  2.38726312e+09
 -1.80269872e+09  6.54591421e+08  1.49473199e+09 -4.54428346e+08
 -4.38055029e+08  8.48586121e+08  2.14839396e+09  9.30740516e+08
  1.94081900e+09  3.29561612e+08  3.84899467e+08 -5.11537776e+08
 -2.45836428e+07 -7.46617247e+08  5.44903386e+07 -9.61246707e+08
 -8.30024003e+08 -6.00477242e+08  8.19997298e+07  2.80268806e+08
  3.90366261e+07  1.79556945e+09 -1.82614080e+09  5.13659541e+08
 -1.93413666e+08  4.22640854e+08 -9.94992634e+08  9.87168296e+08
 -6.42314580e+08 -2.17939788e+09  2.11561511e+09  1.55871056e+08
  1.82761861e+09 -2.13504978e+07  2.03850133e+02 -5.97143396e+08
  1.10586859e+09  1.00433643e+08 -2.28490288e+09 -1.43139109e+09
 -5.71587239e+08 -2.08773579e+08 -1.27392193e+09 -6.64940327e+08
 -6.30760275e+08  4.01437700e+08 -4.22689358e+08  1.13768884e+08
  2.92642728e+08  1.07866039e+07  1.94041783e+09 -7.15034808e+08
  9.04987997e+06 -1.63237590e+09  9.34995133e+08 -5.90649129e+08
 -7.10414069e+06 -5.65714625e+08  3.36403664e+09  3.62955168e+08
 -7.56154274e+08  4.15844541e+09 -1.22138427e+09 -3.84388610e+08
 -4.20105602e+08 -1.33338143e+09  2.49109295e+09 -5.66307850e+08
 -1.77637585e+09 -8.59889834e+08  1.95240928e+09  3.55224633e+09
 -5.43668774e+08 -1.40323720e+09 -1.29809332e+09 -1.94635945e+09
 -4.68303324e+08  1.57356516e+08 -7.93661092e+08  7.00955257e+08
  5.66827244e+08 -2.17933004e+09  7.60140379e+08  1.56114096e+08
 -2.07419506e+09 -3.56858012e+09  1.65473595e+09  1.61513476e+09
  5.27906205e+07 -1.39892051e+09 -5.89687189e+08 -3.70002196e+09
  3.78077960e+08 -2.32925561e+08 -8.30389369e+08 -1.22418199e+09
 -1.30063299e+09  9.97519274e+08 -1.36638516e+09 -9.53214369e+07
  3.75076492e+08  2.98211810e+08 -1.87090058e+09 -2.52223153e+09
 -2.17140787e+09  1.36605533e+09  2.54386759e+08 -2.17701692e+09
 -1.51268873e+08  1.09651328e+09 -1.36005285e+09 -3.16040615e+08
  1.46526631e+09 -2.26403678e+08  9.05142692e+08 -3.05078340e+09
  1.71125337e+09  1.11486291e+09  2.46328518e+09  1.00080096e+09
  9.40577510e+08 -8.30775635e+08 -1.51880478e+08 -2.12124635e+09
  9.61905935e+07 -3.44134255e+08  8.11163537e+08 -1.06954052e+09
 -7.08042531e+08 -3.70678233e+08 -4.36677363e+08  1.93938013e+08
 -4.56589621e+07 -6.87261551e+08  2.06082316e+09 -2.24173456e+09
 -4.11541640e+08  4.81497974e+01 -4.37785956e+08  2.04934253e+08
  9.09845085e+08 -7.80409666e+08 -1.73450337e+08  8.59852200e+08
  9.13345440e+07 -1.29403137e+09  1.61301510e+09 -2.35172785e+09
  3.88769713e+09  1.30580022e+09  1.48310465e+09  1.63583551e+08
  1.06262130e+09  6.41317588e+08  1.35527875e+09 -4.16021799e+08
 -9.26347633e+08 -1.17788260e+09  7.33000157e+08 -1.60164729e+08
 -5.74546448e+07 -6.93987117e+07  4.17981794e+08  2.83575342e+08
 -8.50774405e+08  1.89420608e+08  3.37169369e+08 -2.14342062e+09
  1.33635067e+09 -3.30014318e+08 -2.96925732e+09  1.67983196e+09
  1.34909284e+09  3.09014903e+08  2.42849773e+02  1.41000233e+09
 -1.93119931e+09 -8.07084451e+08  4.40974600e+08  1.64850045e+02
 -4.55675386e+08 -1.10150684e+09  4.76139873e+08 -5.73360433e+08
  3.27585436e+09  8.53381847e+08 -4.98294774e+08 -1.01715057e+08
 -2.37744917e+09 -2.49364567e+07  5.91497021e+01  5.61956909e+08
 -1.42371401e+09  3.96648493e+08 -5.07341840e+08  1.01369043e+08
 -8.67526928e+08  1.00149897e+02  1.48560035e+09 -1.06202661e+09
 -2.23264403e+09 -1.91277990e+09 -1.33002718e+09  3.50953313e+08
  1.05003177e+09  2.95376713e+09  2.12631610e+09 -1.09610044e+08
 -2.15067036e+09  4.90957429e+08  9.57758266e+08 -1.84336740e+09
 -4.78372398e+08  3.45428039e+08 -6.10852991e+08  1.57912229e+09
  7.40950267e+08  2.98914229e+08  1.39042702e+09  7.26803423e+08
 -6.05837986e+08  1.13587809e+09 -1.58870405e+09 -1.88611064e+08
 -3.87645784e+08  8.81651549e+08  1.99326813e+09  5.75367107e+08
 -4.79157891e+08 -3.77618458e+08  7.81116227e+06 -7.63815542e+08
  2.37070854e+09  1.80876832e+09  4.54192418e+08  8.41497746e+01
  9.78698926e+08  2.32252958e+09 -2.70223741e+08 -2.03643737e+08
  1.41191635e+09  3.69014943e+09 -1.66670155e+09 -2.28998025e+09
 -3.34645781e+08 -1.24629054e+09  4.83896674e+08 -2.35043226e+06
 -4.53004641e+08  7.23568298e+08  1.55698698e+08  1.04016664e+09
 -1.37942671e+09 -8.65641957e+08  6.36629728e+08 -4.39632018e+08
  6.72836400e+08  7.60016458e+08  1.40851046e+09  7.65050282e+07
 -3.37678850e+07  3.31087318e+08 -6.96734160e+08  4.58027710e+08
  1.05343742e+09 -2.38670807e+09 -4.13059932e+09  1.52916146e+09
  1.15912472e+09  1.19960562e+09  6.80498219e+08 -2.09146656e+09
 -9.61758672e+08  1.73497051e+09  2.63357676e+09  1.73974423e+08
  1.50135439e+09 -3.32388275e+07 -1.32895086e+08 -2.18936418e+09
  2.36305530e+09  1.73977564e+09 -1.73139006e+09 -2.87737686e+08
  4.64460477e+07  6.42990414e+08 -1.55500557e+08 -4.48237571e+08
  7.40942785e+08 -1.63596453e+09  9.59532374e+08  8.43880594e+08
 -1.74780536e+09  3.29439368e+08 -6.50630900e+08 -1.01769650e+09
 -2.97577075e+08 -4.35299346e+08 -2.29553884e+08 -1.00792644e+07
  1.56985162e+09 -3.01281033e+08 -3.18778634e+09 -3.76876805e+07
  1.17911113e+08 -1.03938660e+08 -1.58534267e+09  3.02026912e+08
 -2.11451153e+09  1.19041458e+09  1.02550407e+09 -8.58677856e+08
 -2.10511216e+09 -8.76461032e+08 -6.49823935e+08  1.18043157e+09
 -8.63873108e+08 -7.06499663e+08  1.58751801e+09 -8.22117306e+07
  6.39515527e+08 -1.09030695e+08  1.41764783e+09  7.35249499e+08
 -2.97999112e+08 -2.66767657e+08 -5.11561210e+08 -1.25949219e+09
  3.10320507e+08 -4.99121874e+08 -2.63849207e+09  3.63162033e+08
  1.19086693e+09  1.29554974e+09 -7.92904722e+08  3.88645962e+07
 -2.88389173e+09 -2.08557916e+09 -1.04819634e+09 -7.45184417e+07
  6.13512759e+08 -5.72152638e+08 -2.65806002e+08  1.02019405e+09
 -2.24081424e+08  4.44166443e+08  2.73375712e+09 -6.87985981e+08
  2.01775523e+08 -8.64117204e+08  3.12581575e+08  8.45624112e+08
  4.40010433e+09  9.88726197e+07 -7.38541393e+08  1.22228661e+09
  2.88264614e+08  8.67702449e+08 -5.27535730e+08  4.52008651e+08
 -6.26176310e+08  1.72955303e+09  5.56023927e+08  6.75644978e+08
  1.17180412e+09  5.75017535e+08 -8.72799612e+08  2.70367450e+09
  1.24000167e+09 -3.96234410e+07 -5.96949746e+08  9.94192510e+08
 -2.21299721e+09 -2.17762700e+09  1.75999990e+02 -6.32739552e+08
  3.53424888e+08 -1.36639122e+09  3.21499734e+01 -3.12593664e+08
 -8.47136359e+08 -1.40921269e+09  1.93520356e+09  1.74858632e+08
  7.55621876e+08 -5.36587456e+06 -7.42598223e+08  1.52479843e+09
 -1.98344723e+08  6.71913186e+08 -5.12860816e+08 -1.83221727e+08
 -5.79890854e+08 -3.41220926e+08 -9.07899059e+08  2.34615813e+09
 -3.50889143e+08 -3.38948028e+08 -5.75297175e+07  5.25701510e+09
  2.80734031e+09 -8.31800519e+06  9.12569531e+08 -2.66198676e+09
  1.13560234e+09 -1.90892682e+09 -1.11868623e+09  1.07585132e+09
  3.12099538e+08  2.06016897e+09  5.26105207e+08  1.36094446e+09
 -1.88700027e+09 -3.39148565e+08  1.55238763e+09 -7.45183428e+07
  1.45007715e+09  1.89879325e+09  1.49545217e+08 -2.44622369e+08
 -8.98327330e+08 -1.62646971e+09  4.65671841e+08  3.83910347e+08
 -1.18362190e+09  1.10274443e+09  2.78959852e+08  1.01595567e+08
 -4.80151145e+08  7.21887813e+08 -8.14623752e+08  4.69665709e+08
  2.83726040e+07 -3.03804662e+09  1.72377773e+08  1.41971760e+08
 -2.51254696e+09 -1.55493256e+09  2.51247036e+09  2.14872903e+09
  2.81557199e+09  4.11298248e+09  1.40201406e+09  2.38076173e+09
 -1.26555354e+09  8.27959567e+07 -2.50424522e+08  1.57388505e+08
 -1.15320052e+09  1.68233333e+09 -1.33050872e+07 -2.86988070e+08
 -7.56121227e+08  3.38358668e+09  1.89149763e+02  7.93203836e+08
  1.53714952e+08  4.95488216e+08 -1.00901508e+09 -7.36598190e+08
 -1.47552414e+09 -6.13773664e+08  3.47370025e+09  7.40428995e+08
  6.27762824e+08  1.17149938e+02 -3.74035682e+08 -6.79813524e+08
 -6.80317416e+08 -5.99679002e+08 -4.40078804e+09 -1.25210596e+09
 -2.20313312e+08  9.15604716e+08  1.59506686e+09  1.32857160e+09
  1.45537065e+09 -1.62508850e+09 -1.42291713e+09 -2.48310772e+09
  1.33441545e+09  9.25664387e+07  1.72631557e+09 -1.23412309e+09
  1.74269451e+08  2.58592150e+09  1.03495812e+09 -2.50042211e+08
  1.21896091e+09  2.52920727e+09  6.62583973e+07  4.28099912e+08
 -8.53299913e+08  1.46019945e+09 -3.59554124e+08  5.38336280e+08
  9.74851696e+08  8.17449018e+07  5.16525989e+08  1.84424206e+09
  3.04749186e+09 -2.28773518e+08  2.22367111e+09 -6.43187022e+07
  1.78092369e+09 -6.77338846e+08  8.88293196e+08  2.43830517e+09
 -1.37710544e+09  1.60723251e+09 -1.07646814e+09 -1.56125746e+09
  1.06346756e+09 -1.19229770e+09  2.15829320e+08  1.89360486e+09
  1.86100997e+09  1.01298194e+09 -3.57723764e+07  1.80174264e+09
  1.63821964e+09  2.53102735e+08 -1.96067482e+09  7.86174238e+08
 -3.46691317e+08 -2.22678331e+08 -8.87092931e+08 -2.48462645e+08
  2.28114213e+09 -1.43982909e+08 -1.31676733e+09  6.71713096e+08
  1.28619923e+09  1.67425230e+08  2.98660330e+09 -1.43228778e+09
  5.39049044e+08 -5.57000067e+08  1.48618791e+09 -9.99144928e+08
  4.74281032e+08  3.26484587e+07  4.37633037e+08 -1.80777108e+09
  1.93836324e+07 -1.25076437e+09  1.15323030e+07 -1.19893839e+09
 -1.20445254e+09  1.07950884e+08 -1.58213949e+09 -2.59380498e+09
  1.00547234e+09  1.52892276e+09  2.75731699e+09 -8.33809967e+08
  2.39923128e+09  7.15210288e+08  3.47271011e+08  1.16137376e+09
 -7.63226051e+08 -5.06636563e+08  1.81958669e+09 -6.69860389e+08
 -1.85964409e+09  1.82588577e+09  1.64122658e+08 -2.01201721e+09
 -1.96852562e+09  1.78330419e+09 -1.40059740e+09  7.62527700e+08
 -1.99767393e+09  6.43931557e+08 -1.38983103e+08 -2.51971956e+09
  3.79499898e+03 -1.03896629e+09  2.32030331e+09 -9.62575115e+08]

In [22]:
rmse = sqrt(mean_squared_error(y_test, ypred_lir))
rmse

1360823886.933968

In [23]:
evaluation = rmse/ (max(y_test))
evaluation

142569.2914545802

In [24]:
ypred_lir = lir.predict(test_data)

In [25]:
submission = pd.DataFrame()
submission["comp_id"] = index_col='comp_id'
submission["views"] = ypred_lir

submission.to_csv('lir_solution.csv', index=False)

In [26]:
from sklearn.pipeline import Pipeline
model_name = 'Multiple Linear Regression'
mlRegressor = LinearRegression()

In [27]:
 mlr_model = Pipeline(steps=[('regressor', mlRegressor)])

In [28]:
mlr_model.fit(X_train,y_train)

Pipeline(steps=[('regressor', LinearRegression())])

In [29]:
y_pred_mlr= mlr_model.predict(X_test)

In [30]:
print(y_pred_mlr)

[ 2.27981111e+08  1.40851056e+09 -3.65966420e+08  2.61088968e+09
 -1.09235160e+09  1.19780901e+09  2.31610676e+09 -1.69261744e+09
 -1.84155326e+09 -1.27811531e+09  8.43667387e+08 -2.86988169e+08
 -3.08331229e+09 -2.10882002e+09 -1.06872782e+09 -2.47648738e+08
 -5.74510759e+08  7.17787865e+08  2.99199721e+08  1.29662417e+09
  6.82050797e+07  1.29606833e+09 -2.35135068e+09  1.71849617e+02
 -8.29282900e+08  4.97068460e+07 -4.58507197e+08 -6.79689989e+08
  1.61849980e+02 -1.33027896e+09  2.58050498e+09  1.02383883e+09
  3.51544461e+08  2.41849885e+02  1.58064762e+08 -1.44300129e+09
 -3.39940441e+08  5.53429938e+08  2.37391001e+09 -2.44112021e+09
  1.81811685e+09  1.67849887e+02 -1.25386439e+09  1.21749187e+08
  4.61499348e+01  2.11739836e+09  5.09257096e+08  4.70219208e+08
 -2.72523113e+08  6.34474575e+07 -2.99397447e+08  1.16967303e+09
 -1.42359408e+09  1.06780253e+09 -2.15630753e+08  1.79758614e+09
  2.21363269e+09  4.31657796e+07 -1.73834356e+09  5.52443842e+08
 -1.20500642e+09  3.63321808e+08  2.15113311e+09 -1.99855156e+09
  3.12307571e+08  2.35898544e+09 -7.40936683e+08  5.43028786e+08
 -1.04048474e+09 -7.24250388e+08  3.84663257e+08 -1.99981100e+09
 -2.47807668e+09 -1.11500221e+09 -5.21968432e+07  1.77378903e+08
  7.54239491e+08  5.50766758e+08  2.10934979e+09  3.05017768e+08
 -3.72887552e+08  1.00144274e+08 -2.12428234e+09 -1.03300107e+09
 -1.21819810e+09 -6.93667645e+07 -3.90874597e+08  2.33812754e+09
 -2.12124660e+08  2.48897216e+07  4.32768949e+08 -7.12682984e+08
 -1.22295593e+08  2.92615444e+07 -1.44528132e+09  2.35561390e+08
  7.41685594e+08  6.61498690e+01  4.39831304e+08  7.84085150e+08
  1.69684372e+09  1.37306983e+07 -2.13503990e+07 -5.61796112e+08
  1.17752910e+09 -2.55483756e+09 -7.35246365e+08 -2.59128050e+09
  1.78849869e+02 -1.59237538e+08  1.06274884e+09  1.42940037e+09
  1.91246899e+09  2.10677335e+09  1.48972479e+08  1.80826757e+09
 -1.55342357e+09  8.64062065e+08 -6.30760374e+08 -3.93755160e+08
  2.27874446e+09 -2.54004386e+09  2.83402987e+08 -2.72313800e+09
 -9.32810194e+08  1.42053020e+09 -2.68389717e+09 -4.78372299e+08
 -5.77317834e+08  1.25075662e+09  6.46719054e+08 -1.04411394e+09
 -7.67598654e+08 -8.74069711e+08 -1.75034172e+09 -2.87246431e+08
  2.96447096e+08  2.96242816e+09 -1.28775136e+09 -1.98092692e+09
  9.97710173e+08 -1.25349214e+09  1.74249752e+09  1.76656605e+09
 -8.19512177e+08  6.69301169e+08  1.08308009e+09 -5.80089920e+08
  2.94175014e+09 -7.52847796e+08 -5.23922627e+08  1.37814235e+09
  9.74748938e+08  1.46261819e+08 -1.01924108e+09 -9.27571754e+08
  1.89439544e+09 -2.04171904e+08  7.51501245e+01  1.27522164e+09
 -6.42602281e+07 -8.91178453e+08 -2.28782456e+08 -3.54175127e+08
 -1.02395556e+09  6.89699754e+08  7.59870640e+08 -1.95209808e+07
  2.72003945e+08 -3.84878137e+08  7.90354537e+08  1.22855388e+09
 -1.53294970e+09  5.27083679e+08  4.66026758e+08 -2.02385592e+08
  1.46203408e+09 -1.61740250e+09  1.70356432e+08  9.06334862e+08
 -1.60805712e+09 -1.53111887e+09  1.76460863e+09 -1.16430710e+09
 -7.95049852e+08 -5.74523973e+08 -2.13238509e+09 -1.66198512e+09
 -1.16305704e+09 -1.01960693e+09 -1.06617317e+09  2.12466150e+08
  1.67590284e+09 -1.44333736e+09 -5.43360370e+08  2.54965110e+09
  2.41556650e+09 -8.86999346e+08 -2.98163446e+08  8.13770294e+08
  1.76126928e+09  8.91559340e+08 -8.78627714e+08  1.19266051e+09
 -2.78184099e+09 -2.18978091e+09  7.07811558e+08  6.74227246e+07
  7.82694500e+08 -6.67098587e+08 -3.36690899e+09  5.83261107e+07
 -1.79164761e+07 -1.42124473e+09 -1.33647007e+09 -7.16949682e+08
 -5.42946211e+07 -7.38541492e+08  2.50699538e+02 -7.34068267e+07
 -1.44282808e+09  3.12531633e+09  2.56734489e+08  4.53501867e+08
  7.24875819e+08 -5.26404635e+08 -2.36756590e+09  4.20467313e+09
  2.03770585e+08 -7.90197010e+08  2.42589065e+09  1.32265105e+09
  1.71774783e+02  6.51169062e+08 -1.75166540e+09  9.37212453e+08
  1.91261593e+08  8.74370122e+08  2.45282693e+08  4.92226046e+08
  7.65051270e+07 -9.58095246e+08  1.80566787e+09 -1.67375673e+09
 -1.23132186e+08 -1.52255658e+09 -1.13928803e+09  4.72247895e+09
 -8.85829918e+07  2.75557657e+09  4.61557283e+08 -4.89278721e+08
 -6.13807923e+08 -2.16280597e+09 -5.56711309e+08  2.76504640e+08
  6.50830959e+08  5.14989884e+08  5.51498370e+01 -2.90010087e+08
 -1.39087390e+09 -2.79276018e+09 -1.86087402e+09  2.20141318e+09
 -1.64467925e+09 -2.91515737e+09 -1.00802992e+09 -2.87455576e+08
 -3.47239836e+08 -1.98092682e+09 -4.12029785e+08  1.89251288e+09
  1.23955318e+09  4.23937327e+07  5.50766704e+08  5.27169663e+07
  4.05498364e+09 -1.07808641e+08  1.10064677e+09  3.79499898e+03
 -8.27856203e+08  1.70227240e+09  2.89536839e+09 -9.88161766e+08
 -8.30024102e+08  1.28026034e+09  2.16998978e+09  2.04621599e+09
  1.76858483e+09  4.59154160e+07  3.88890345e+08 -1.47377399e+08
  8.01501384e+01  4.45160606e+08 -5.06225780e+08  6.36203478e+07
 -6.54551953e+08 -1.76029201e+09  6.94641583e+08  3.09461753e+08
 -2.99620310e+09 -3.36749053e+08 -3.64819824e+08 -3.98048961e+08
  4.68687549e+08  1.84356176e+09  3.38358658e+09  2.47186066e+09
  9.72120810e+08  1.76294936e+09  4.81049898e+08  1.48855587e+09
  7.67603798e+08  5.94309410e+08  7.35353630e+08  8.43329804e+06
 -1.13788447e+09  2.43648546e+09 -2.72107980e+08  2.38726312e+09
 -1.80269872e+09  6.54591421e+08  1.49473199e+09 -4.54428346e+08
 -4.38055029e+08  8.48586121e+08  2.14839396e+09  9.30740516e+08
  1.94081900e+09  3.29561612e+08  3.84899467e+08 -5.11537776e+08
 -2.45836428e+07 -7.46617247e+08  5.44903386e+07 -9.61246707e+08
 -8.30024003e+08 -6.00477242e+08  8.19997298e+07  2.80268806e+08
  3.90366261e+07  1.79556945e+09 -1.82614080e+09  5.13659541e+08
 -1.93413666e+08  4.22640854e+08 -9.94992634e+08  9.87168296e+08
 -6.42314580e+08 -2.17939788e+09  2.11561511e+09  1.55871056e+08
  1.82761861e+09 -2.13504978e+07  2.03850133e+02 -5.97143396e+08
  1.10586859e+09  1.00433643e+08 -2.28490288e+09 -1.43139109e+09
 -5.71587239e+08 -2.08773579e+08 -1.27392193e+09 -6.64940327e+08
 -6.30760275e+08  4.01437700e+08 -4.22689358e+08  1.13768884e+08
  2.92642728e+08  1.07866039e+07  1.94041783e+09 -7.15034808e+08
  9.04987997e+06 -1.63237590e+09  9.34995133e+08 -5.90649129e+08
 -7.10414069e+06 -5.65714625e+08  3.36403664e+09  3.62955168e+08
 -7.56154274e+08  4.15844541e+09 -1.22138427e+09 -3.84388610e+08
 -4.20105602e+08 -1.33338143e+09  2.49109295e+09 -5.66307850e+08
 -1.77637585e+09 -8.59889834e+08  1.95240928e+09  3.55224633e+09
 -5.43668774e+08 -1.40323720e+09 -1.29809332e+09 -1.94635945e+09
 -4.68303324e+08  1.57356516e+08 -7.93661092e+08  7.00955257e+08
  5.66827244e+08 -2.17933004e+09  7.60140379e+08  1.56114096e+08
 -2.07419506e+09 -3.56858012e+09  1.65473595e+09  1.61513476e+09
  5.27906205e+07 -1.39892051e+09 -5.89687189e+08 -3.70002196e+09
  3.78077960e+08 -2.32925561e+08 -8.30389369e+08 -1.22418199e+09
 -1.30063299e+09  9.97519274e+08 -1.36638516e+09 -9.53214369e+07
  3.75076492e+08  2.98211810e+08 -1.87090058e+09 -2.52223153e+09
 -2.17140787e+09  1.36605533e+09  2.54386759e+08 -2.17701692e+09
 -1.51268873e+08  1.09651328e+09 -1.36005285e+09 -3.16040615e+08
  1.46526631e+09 -2.26403678e+08  9.05142692e+08 -3.05078340e+09
  1.71125337e+09  1.11486291e+09  2.46328518e+09  1.00080096e+09
  9.40577510e+08 -8.30775635e+08 -1.51880478e+08 -2.12124635e+09
  9.61905935e+07 -3.44134255e+08  8.11163537e+08 -1.06954052e+09
 -7.08042531e+08 -3.70678233e+08 -4.36677363e+08  1.93938013e+08
 -4.56589621e+07 -6.87261551e+08  2.06082316e+09 -2.24173456e+09
 -4.11541640e+08  4.81497974e+01 -4.37785956e+08  2.04934253e+08
  9.09845085e+08 -7.80409666e+08 -1.73450337e+08  8.59852200e+08
  9.13345440e+07 -1.29403137e+09  1.61301510e+09 -2.35172785e+09
  3.88769713e+09  1.30580022e+09  1.48310465e+09  1.63583551e+08
  1.06262130e+09  6.41317588e+08  1.35527875e+09 -4.16021799e+08
 -9.26347633e+08 -1.17788260e+09  7.33000157e+08 -1.60164729e+08
 -5.74546448e+07 -6.93987117e+07  4.17981794e+08  2.83575342e+08
 -8.50774405e+08  1.89420608e+08  3.37169369e+08 -2.14342062e+09
  1.33635067e+09 -3.30014318e+08 -2.96925732e+09  1.67983196e+09
  1.34909284e+09  3.09014903e+08  2.42849773e+02  1.41000233e+09
 -1.93119931e+09 -8.07084451e+08  4.40974600e+08  1.64850045e+02
 -4.55675386e+08 -1.10150684e+09  4.76139873e+08 -5.73360433e+08
  3.27585436e+09  8.53381847e+08 -4.98294774e+08 -1.01715057e+08
 -2.37744917e+09 -2.49364567e+07  5.91497021e+01  5.61956909e+08
 -1.42371401e+09  3.96648493e+08 -5.07341840e+08  1.01369043e+08
 -8.67526928e+08  1.00149897e+02  1.48560035e+09 -1.06202661e+09
 -2.23264403e+09 -1.91277990e+09 -1.33002718e+09  3.50953313e+08
  1.05003177e+09  2.95376713e+09  2.12631610e+09 -1.09610044e+08
 -2.15067036e+09  4.90957429e+08  9.57758266e+08 -1.84336740e+09
 -4.78372398e+08  3.45428039e+08 -6.10852991e+08  1.57912229e+09
  7.40950267e+08  2.98914229e+08  1.39042702e+09  7.26803423e+08
 -6.05837986e+08  1.13587809e+09 -1.58870405e+09 -1.88611064e+08
 -3.87645784e+08  8.81651549e+08  1.99326813e+09  5.75367107e+08
 -4.79157891e+08 -3.77618458e+08  7.81116227e+06 -7.63815542e+08
  2.37070854e+09  1.80876832e+09  4.54192418e+08  8.41497746e+01
  9.78698926e+08  2.32252958e+09 -2.70223741e+08 -2.03643737e+08
  1.41191635e+09  3.69014943e+09 -1.66670155e+09 -2.28998025e+09
 -3.34645781e+08 -1.24629054e+09  4.83896674e+08 -2.35043226e+06
 -4.53004641e+08  7.23568298e+08  1.55698698e+08  1.04016664e+09
 -1.37942671e+09 -8.65641957e+08  6.36629728e+08 -4.39632018e+08
  6.72836400e+08  7.60016458e+08  1.40851046e+09  7.65050282e+07
 -3.37678850e+07  3.31087318e+08 -6.96734160e+08  4.58027710e+08
  1.05343742e+09 -2.38670807e+09 -4.13059932e+09  1.52916146e+09
  1.15912472e+09  1.19960562e+09  6.80498219e+08 -2.09146656e+09
 -9.61758672e+08  1.73497051e+09  2.63357676e+09  1.73974423e+08
  1.50135439e+09 -3.32388275e+07 -1.32895086e+08 -2.18936418e+09
  2.36305530e+09  1.73977564e+09 -1.73139006e+09 -2.87737686e+08
  4.64460477e+07  6.42990414e+08 -1.55500557e+08 -4.48237571e+08
  7.40942785e+08 -1.63596453e+09  9.59532374e+08  8.43880594e+08
 -1.74780536e+09  3.29439368e+08 -6.50630900e+08 -1.01769650e+09
 -2.97577075e+08 -4.35299346e+08 -2.29553884e+08 -1.00792644e+07
  1.56985162e+09 -3.01281033e+08 -3.18778634e+09 -3.76876805e+07
  1.17911113e+08 -1.03938660e+08 -1.58534267e+09  3.02026912e+08
 -2.11451153e+09  1.19041458e+09  1.02550407e+09 -8.58677856e+08
 -2.10511216e+09 -8.76461032e+08 -6.49823935e+08  1.18043157e+09
 -8.63873108e+08 -7.06499663e+08  1.58751801e+09 -8.22117306e+07
  6.39515527e+08 -1.09030695e+08  1.41764783e+09  7.35249499e+08
 -2.97999112e+08 -2.66767657e+08 -5.11561210e+08 -1.25949219e+09
  3.10320507e+08 -4.99121874e+08 -2.63849207e+09  3.63162033e+08
  1.19086693e+09  1.29554974e+09 -7.92904722e+08  3.88645962e+07
 -2.88389173e+09 -2.08557916e+09 -1.04819634e+09 -7.45184417e+07
  6.13512759e+08 -5.72152638e+08 -2.65806002e+08  1.02019405e+09
 -2.24081424e+08  4.44166443e+08  2.73375712e+09 -6.87985981e+08
  2.01775523e+08 -8.64117204e+08  3.12581575e+08  8.45624112e+08
  4.40010433e+09  9.88726197e+07 -7.38541393e+08  1.22228661e+09
  2.88264614e+08  8.67702449e+08 -5.27535730e+08  4.52008651e+08
 -6.26176310e+08  1.72955303e+09  5.56023927e+08  6.75644978e+08
  1.17180412e+09  5.75017535e+08 -8.72799612e+08  2.70367450e+09
  1.24000167e+09 -3.96234410e+07 -5.96949746e+08  9.94192510e+08
 -2.21299721e+09 -2.17762700e+09  1.75999990e+02 -6.32739552e+08
  3.53424888e+08 -1.36639122e+09  3.21499734e+01 -3.12593664e+08
 -8.47136359e+08 -1.40921269e+09  1.93520356e+09  1.74858632e+08
  7.55621876e+08 -5.36587456e+06 -7.42598223e+08  1.52479843e+09
 -1.98344723e+08  6.71913186e+08 -5.12860816e+08 -1.83221727e+08
 -5.79890854e+08 -3.41220926e+08 -9.07899059e+08  2.34615813e+09
 -3.50889143e+08 -3.38948028e+08 -5.75297175e+07  5.25701510e+09
  2.80734031e+09 -8.31800519e+06  9.12569531e+08 -2.66198676e+09
  1.13560234e+09 -1.90892682e+09 -1.11868623e+09  1.07585132e+09
  3.12099538e+08  2.06016897e+09  5.26105207e+08  1.36094446e+09
 -1.88700027e+09 -3.39148565e+08  1.55238763e+09 -7.45183428e+07
  1.45007715e+09  1.89879325e+09  1.49545217e+08 -2.44622369e+08
 -8.98327330e+08 -1.62646971e+09  4.65671841e+08  3.83910347e+08
 -1.18362190e+09  1.10274443e+09  2.78959852e+08  1.01595567e+08
 -4.80151145e+08  7.21887813e+08 -8.14623752e+08  4.69665709e+08
  2.83726040e+07 -3.03804662e+09  1.72377773e+08  1.41971760e+08
 -2.51254696e+09 -1.55493256e+09  2.51247036e+09  2.14872903e+09
  2.81557199e+09  4.11298248e+09  1.40201406e+09  2.38076173e+09
 -1.26555354e+09  8.27959567e+07 -2.50424522e+08  1.57388505e+08
 -1.15320052e+09  1.68233333e+09 -1.33050872e+07 -2.86988070e+08
 -7.56121227e+08  3.38358668e+09  1.89149763e+02  7.93203836e+08
  1.53714952e+08  4.95488216e+08 -1.00901508e+09 -7.36598190e+08
 -1.47552414e+09 -6.13773664e+08  3.47370025e+09  7.40428995e+08
  6.27762824e+08  1.17149938e+02 -3.74035682e+08 -6.79813524e+08
 -6.80317416e+08 -5.99679002e+08 -4.40078804e+09 -1.25210596e+09
 -2.20313312e+08  9.15604716e+08  1.59506686e+09  1.32857160e+09
  1.45537065e+09 -1.62508850e+09 -1.42291713e+09 -2.48310772e+09
  1.33441545e+09  9.25664387e+07  1.72631557e+09 -1.23412309e+09
  1.74269451e+08  2.58592150e+09  1.03495812e+09 -2.50042211e+08
  1.21896091e+09  2.52920727e+09  6.62583973e+07  4.28099912e+08
 -8.53299913e+08  1.46019945e+09 -3.59554124e+08  5.38336280e+08
  9.74851696e+08  8.17449018e+07  5.16525989e+08  1.84424206e+09
  3.04749186e+09 -2.28773518e+08  2.22367111e+09 -6.43187022e+07
  1.78092369e+09 -6.77338846e+08  8.88293196e+08  2.43830517e+09
 -1.37710544e+09  1.60723251e+09 -1.07646814e+09 -1.56125746e+09
  1.06346756e+09 -1.19229770e+09  2.15829320e+08  1.89360486e+09
  1.86100997e+09  1.01298194e+09 -3.57723764e+07  1.80174264e+09
  1.63821964e+09  2.53102735e+08 -1.96067482e+09  7.86174238e+08
 -3.46691317e+08 -2.22678331e+08 -8.87092931e+08 -2.48462645e+08
  2.28114213e+09 -1.43982909e+08 -1.31676733e+09  6.71713096e+08
  1.28619923e+09  1.67425230e+08  2.98660330e+09 -1.43228778e+09
  5.39049044e+08 -5.57000067e+08  1.48618791e+09 -9.99144928e+08
  4.74281032e+08  3.26484587e+07  4.37633037e+08 -1.80777108e+09
  1.93836324e+07 -1.25076437e+09  1.15323030e+07 -1.19893839e+09
 -1.20445254e+09  1.07950884e+08 -1.58213949e+09 -2.59380498e+09
  1.00547234e+09  1.52892276e+09  2.75731699e+09 -8.33809967e+08
  2.39923128e+09  7.15210288e+08  3.47271011e+08  1.16137376e+09
 -7.63226051e+08 -5.06636563e+08  1.81958669e+09 -6.69860389e+08
 -1.85964409e+09  1.82588577e+09  1.64122658e+08 -2.01201721e+09
 -1.96852562e+09  1.78330419e+09 -1.40059740e+09  7.62527700e+08
 -1.99767393e+09  6.43931557e+08 -1.38983103e+08 -2.51971956e+09
  3.79499898e+03 -1.03896629e+09  2.32030331e+09 -9.62575115e+08]

In [31]:
rmse = sqrt(mean_squared_error(y_test, y_pred_mlr))
rmse

1360823886.933968

In [32]:
evaluation = rmse/ (max(y_test))
evaluation

142569.2914545802

In [33]:
y_pred_mlr = mlr_model.predict(test_data)

In [34]:
submission = pd.DataFrame()
submission["comp_id"] = index_col='comp_id'
submission["views"] = ypred_lir

submission.to_csv('mlr_solution.csv', index=False)

In [35]:
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2)

In [36]:
clf = LinearRegression(n_jobs=-1)

In [37]:
clf.fit(X_train, y_train)

LinearRegression(n_jobs=-1)

In [38]:
ypred = clf.predict(X_test)

In [39]:
print(ypred)

[-2.24607714e+10 -1.27754493e+10  6.32627140e+08 -1.74737493e+10
  1.36341640e+10 -2.85230210e+10  3.56777835e+09  5.09072101e+09
  1.48966793e+09 -9.41184890e+09  8.29499491e+09 -1.01627698e+10
 -6.59322604e+09 -8.42985677e+09 -1.75087275e+10  3.86282861e+09
 -5.97935759e+09 -1.22123155e+10 -1.43246031e+09  4.26766510e+09
 -3.17516570e+09  1.58933469e+09 -7.42765561e+09 -6.89894704e+09
  9.57691377e+09  7.26298996e+09 -2.13918914e+10 -2.74771505e+09
 -8.74365427e+09 -6.29258932e+09  7.91549297e+09  1.00032995e+10
 -9.34846391e+09 -3.54445030e+09  7.57379151e+09 -1.15995688e+10
  2.71923319e+09  2.11022941e+10  1.16772195e+10 -1.65456260e+10
 -3.80211696e+09 -1.21430169e+08  7.37009204e+09  5.06969931e+09
  1.53956108e+10 -8.16362414e+09 -2.47541547e+09  3.17116394e+09
  1.42672458e+08 -4.41258042e+09  5.14372822e+09 -9.09440080e+09
  8.52158697e+09 -1.77974346e+10  2.27579755e+10  6.32991896e+08
  4.79655119e+09  1.60682925e+10 -7.30503814e+09  3.04179964e+09
  1.29188474e+10 -2.54673665e+09 -1.85394694e+10  3.57474876e+09
  1.11764103e+10  2.08872578e+10 -8.79251576e+08  4.98729696e+09
 -1.26879316e+10  3.84993636e+09 -3.42274724e+09 -2.82816110e+10
  8.59689602e+09  1.86902326e+10 -9.72681280e+09 -5.70182432e+08
  1.58227345e+02  1.84777538e+10 -2.44837980e+09  8.77904049e+09
 -7.51842310e+09  2.52699547e+09  9.65588296e+09  2.06808240e+08
  8.44678551e+09  1.29153057e+10  1.53534849e+10  1.46647392e+10
  8.88298842e+09  4.83581667e+09  1.20198843e+09  4.39903328e+09
 -9.24507625e+09  1.21614932e+09  3.63391812e+08  6.50239853e+09
 -3.27319411e+09  3.77617280e+09  1.38957094e+09 -1.28257850e+10
  5.78631781e+09  2.58723810e+10  3.57663225e+09 -1.39062374e+10
  8.09984360e+01  1.47212686e+08 -1.08749617e+10  9.89056869e+09
 -3.66064966e+09 -2.89069957e+09  1.62341781e+10  2.80321657e+09
 -9.81360397e+09  1.27556524e+10  6.68085329e+09 -2.32314885e+10
  6.28498893e+09 -1.96729927e+10  1.22527567e+10 -1.40943887e+10
  1.12181245e+10  3.82821373e+10  1.18082946e+10  3.82124965e+09
 -3.44468723e+09 -5.66922445e+09  7.03143531e+09 -1.77698960e+09
 -9.22848054e+09  2.29505717e+09  1.27522109e+10 -4.31553505e+09
 -8.60645543e+08 -3.10849447e+10 -1.37522646e+10  5.20371399e+09
 -7.25116659e+09 -1.25451705e+10  1.96010650e+10  1.76905413e+09
  1.25774857e+02 -6.34860381e+09 -4.95969658e+09  7.97748032e+01
  1.94181001e+09  6.57751389e+01 -1.23553697e+10 -6.69952911e+09
 -4.82683913e+09 -9.94135946e+08  4.40739603e+09  7.60024127e+09
 -8.49739698e+09  1.13314332e+10 -4.40440547e+09  5.55160649e+09
 -3.38442714e+10 -3.20589443e+10 -2.26169046e+10  2.75176802e+10
  1.62511394e+10  1.17240779e+09  1.92074115e+10  1.77861235e+10
 -7.39156356e+09 -1.43719851e+09 -1.01845341e+10 -3.65420867e+09
  1.61328984e+10  3.63551687e+08  1.14519654e+10 -3.93946936e+09
  1.92168358e+10 -1.16030262e+10  4.34672085e+09 -8.88366452e+08
 -1.80670956e+10 -1.85942617e+10  2.25633617e+09 -3.82682709e+09
  7.99719041e+09  1.71946133e+09  9.07738304e+01 -8.61370719e+09
  4.33402947e+09  6.54129761e+09  1.03552291e+10 -1.15059032e+10
  2.99907642e+09 -2.47577151e+10  2.73021614e+09 -1.33376387e+10
 -6.12216588e+09  2.81802590e+10  1.77125429e+10 -3.01867083e+09
 -7.90109061e+09 -9.06518803e+09  2.94091525e+10 -3.12639895e+09
  1.01071832e+10  7.54775824e+09  4.19722396e+09  2.20590723e+10
 -6.15339599e+08  1.17793443e+10  3.40695791e+09  5.52117674e+09
  6.55500752e+09  3.52618457e+08 -1.55419951e+10 -2.10965690e+10
  1.47245284e+10  7.51403026e+09 -3.10479116e+09  1.26558469e+10
  1.05809735e+10  6.88283560e+09  1.78742830e+09  1.99469318e+10
  2.06930419e+10 -5.72388304e+09  3.72073507e+09 -4.24205258e+09
 -2.21739909e+09  1.34045127e+10  6.47755890e+01 -2.76084670e+09
 -1.19198997e+09  1.41226685e+02  7.51691911e+09  1.09571934e+09
 -1.33786987e+10 -1.00624323e+10 -1.04421693e+10 -2.07849087e+10
 -3.12880269e+10 -5.72094003e+09 -1.94380787e+10  8.19322066e+09
 -3.24348761e+09  1.63224819e+02 -4.65572920e+08  5.51970079e+09
 -6.89290053e+09 -1.28713135e+10  1.22763484e+10  2.33668371e+08
  2.39556207e+10  1.88526797e+10 -1.14863237e+10  1.94626006e+10
 -5.37360923e+09 -2.84690153e+09  1.76858304e+10  1.68410640e+09
  1.54227093e+02 -4.45701769e+09  4.04053426e+09  1.22346495e+10
 -4.78368955e+09 -1.09304436e+09  1.05481963e+09  5.07748566e+01
 -8.37535464e+09  2.74714814e+10  1.16284291e+10 -8.40796966e+09
 -6.38398516e+09 -6.69920323e+09  8.74196177e+09  8.65432458e+08
  8.83053124e+08  1.36515115e+09  4.54015065e+09  3.17498023e+09
 -7.02630884e+09  2.14299460e+10  2.25154067e+10  8.67724838e+01
 -2.29536200e+10 -1.90198471e+10  5.44869071e+09 -1.41492308e+10
  3.23293888e+09 -4.26036103e+09  6.11481301e+09  7.46111730e+09
 -1.21472918e+10 -9.21418493e+09  9.10235030e+09  2.21415800e+10
 -1.32905517e+10  1.13146345e+10 -2.03313542e+10 -2.04380894e+10
 -4.87436779e+09 -1.67702941e+09  6.26468141e+09  6.25941814e+09
  8.92514936e+09  2.11953101e+08  1.99225647e+02  4.59972276e+09
 -2.01448082e+10  2.08013856e+10  3.65949103e+09 -2.46092963e+10
  1.11806202e+09  2.83476330e+09  3.82449465e+10 -7.78882711e+09
  1.76714175e+09 -1.47021447e+10 -3.07007567e+10  3.37144124e+09
 -1.30721586e+10  9.88504721e+08 -3.43571422e+09  5.87728424e+01
  6.32294736e+09  1.72800287e+09 -6.86444914e+09  2.02477405e+08
 -7.29338924e+09 -1.49946761e+10  1.80051029e+10 -4.93306310e+09
 -6.60642021e+09 -9.79718995e+09  1.19450834e+10  1.25550114e+10
 -7.34658265e+09 -1.84532804e+10 -3.10087046e+10  1.05483296e+10
  1.82905677e+10 -1.28572445e+10  5.03817549e+09 -2.90085367e+10
  5.36466566e+09  4.20632824e+09  1.46985856e+10 -1.05666634e+09
 -1.98949702e+10 -1.00987873e+10  5.09410241e+08  1.15791881e+08
  1.24363304e+10 -4.91954131e+09  2.41551144e+10  6.33616915e+09
  4.98628828e+09 -2.12712725e+10  2.29287029e+10  2.41974929e+10
 -1.71850314e+10 -1.04935752e+09  1.23645438e+10  1.78383271e+10
  1.70629383e+10  5.29817712e+09  8.26211418e+09 -3.59558135e+09
  1.10698441e+10  9.76336196e+09 -2.97598822e+10 -1.03318697e+09
  3.43110688e+08 -1.07534940e+10 -6.34562868e+09  4.40787982e+09
 -1.44095464e+10 -7.50019255e+08  1.20863985e+10 -5.97225929e+09
 -5.82425423e+08  6.65412134e+09  4.16708570e+08  2.15430630e+10
  4.04891897e+09  2.19855840e+10  1.95224506e+02  1.10040980e+10
 -1.42366431e+10 -1.02810952e+10 -2.68153598e+09 -1.38741078e+10
  9.18717171e+09 -4.03041465e+09 -1.11897877e+10 -7.59402908e+09
 -1.84081322e+10 -1.65613093e+10 -1.30899217e+10  1.04205009e+10
  1.59319068e+10 -1.21796850e+10 -1.37401982e+10 -1.66191047e+10
 -4.92695451e+09 -5.55563732e+09  3.96118051e+10 -3.88824460e+10
 -7.27571460e+09  2.30856824e+09  2.01427900e+10  7.96707781e+09
 -1.29610980e+10 -7.70134724e+09  2.76127088e+09 -2.81535880e+09
 -1.31481270e+10  1.36699364e+02 -7.11881164e+08 -4.74803127e+09
 -5.34346560e+09  1.27159449e+10 -4.46500333e+03 -2.08354709e+09
  5.01137615e+09  2.38224785e+02 -2.26600794e+09  8.50354701e+09
 -2.18712571e+10  1.52363531e+10  8.89076002e+09 -5.64628588e+09
  1.64957350e+09 -4.13795426e+09 -2.06290328e+10 -9.17947983e+09
  4.36414851e+09 -7.08049873e+09  1.27550926e+10  6.02926926e+09
  5.33732786e+09 -2.34635912e+10  2.34648065e+10 -1.77813470e+10
  7.96908813e+09  8.52545280e+09 -1.31288068e+10  4.19053334e+09
  4.41045745e+09 -4.50272961e+09 -1.03683688e+10 -3.15454582e+10
  2.14225983e+02  3.01382892e+10 -9.47613087e+08 -4.82348747e+09
 -7.41646198e+09  3.95827102e+09 -2.00630766e+09  1.10817142e+10
 -1.77048564e+08  1.07636003e+10  1.67262780e+10  8.64065415e+08
 -1.84392134e+09 -2.21649865e+10  7.60785382e+09  1.75245945e+10
  6.70920722e+09  4.78456650e+08  1.14045819e+10 -2.53301108e+09
  4.59019052e+09 -3.33952274e+09  1.19789567e+09 -2.92680749e+10
  8.53778912e+09 -9.11463025e+09  5.93158328e+07 -2.09396751e+09
  5.19255859e+09  5.44594513e+09 -9.08643491e+09  2.93945752e+09
  4.12312493e+08 -9.08322751e+09  1.97227533e+10 -5.09740149e+09
 -6.33471148e+09 -6.19229277e+09 -1.02738837e+10  6.86166299e+09
 -4.71544240e+09  1.49992366e+10  1.91408403e+09 -9.89185285e+09
 -2.30323879e+10  3.77014124e+09 -2.46357085e+08  7.69428609e+09
 -2.19389463e+10  1.95593690e+09  1.02586150e+09  7.47730370e+01
  1.68721280e+09 -1.29096556e+10 -4.43269715e+09  1.16179536e+09
  2.17744352e+10 -1.02255042e+10  3.25378899e+10  1.38031372e+10
  3.67975580e+10  1.67262779e+10  5.07743359e+10 -1.91281518e+10
  1.12788495e+10  6.74078409e+09  7.08576928e+09  1.58643010e+10
  2.07617240e+09  1.82310010e+09  2.48452996e+10  7.39328270e+08
 -2.13623172e+10 -1.36612404e+10 -1.81113885e+10  8.21123456e+09
 -1.99899103e+09 -2.66629985e+09 -1.24625898e+10  5.30398283e+09
 -1.60239076e+10 -5.08248736e+09 -2.04804484e+10  2.02423428e+10
 -8.47654405e+09  3.01747326e+10 -8.78483540e+09  1.95338464e+10
 -2.20768814e+10  1.90138768e+09 -1.38805585e+10 -6.80542881e+09
 -2.40764507e+10  1.78376031e+10 -7.39625955e+07  1.32532583e+09
  1.05159908e+09  7.14479738e+09  1.73244508e+10  1.38957084e+09
  4.67214213e+09  9.86378634e+09 -2.34546447e+10 -1.88274435e+09
  5.70944615e+09 -8.14596809e+09 -6.55290871e+09 -1.31616608e+10
 -6.78423949e+08 -5.97576987e+09 -8.28882029e+09  1.44815923e+10
 -1.26786784e+10  1.23465848e+10 -7.55355992e+09 -1.05020698e+10
  1.09984718e+10 -2.49705127e+10  2.15619268e+10  1.31636885e+10
 -9.81512492e+09  7.79168129e+07  9.38644936e+09 -6.02539761e+09
 -1.91581949e+10  8.08810577e+09  2.81851204e+10 -5.10990213e+08
 -1.07745302e+09 -4.99003145e+08  9.47736282e+01 -5.54160891e+09
  5.12447349e+09  7.72519722e+09  1.98683624e+10 -4.40156463e+09
 -1.34384752e+10  1.72580956e+10 -2.99369728e+10  1.89321583e+10
  1.09083626e+10  3.77018653e+09  1.68048392e+10 -1.54549311e+10
  9.88596853e+09 -1.40780378e+10  2.45603562e+09 -1.19879264e+10
 -1.01952205e+10 -1.69962357e+10 -1.10283904e+10 -1.26638649e+08]

In [40]:
rmse = sqrt(mean_squared_error(y_test, ypred))
rmse

12704392681.54873

In [41]:
evaluation = rmse/ (max(y_test))
evaluation

1363571.1797304638

In [42]:
ypred = clf.predict(test_data)

In [43]:
submission = pd.DataFrame()
submission["comp_id"] = index_col='comp_id'
submission["views"] = ypred

submission.to_csv('sol_ypred.csv', index=False)

In [44]:
from pycaret.regression import *
regression = setup(data = train_data,  target = 'views')

In [ ]:
best_model = compare_models()

IntProgress(value=0, description='Processing: ', max=99)

Initiated  . . . . . . . . . . . . . . . . . .                 19:49:42
Status     . . . . . . . . . . . . . . . . . .         Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Decision Tree Regressor

In [ ]:
print(best_models)